#!/bin/bash
#SBATCH --job-name=brake
#SBATCH	-N 1
#SBATCH -n 8
#SBATCH -t 2-00:00:00
#SBATCH	-o run.out
#SBATCH -e error.out
#SBATCH --mail-type=END
#SBATCH --mail-user=ericm628@gmail.com

source $HOME/.bashrc
srun $HOME/ramses-boris/bin/ramses3d mhd_part.nml
