# Script to merge coverage files generated by gcov
# Author: Noe Brucy, Tine Colman
# Known issues:
# - in rt_spectra, gcov identified some variable declarations as executed.
# - in turb_force_utils, stop is identified as a branch

import os
import re
from collections import defaultdict
from glob import glob

class GCovParser:
    def __init__(self):
        # Dictionary to store data as {source_file: {line_number: (execution_count, line_content)}}
        self.coverage_data = defaultdict(lambda: defaultdict(lambda: ("-", "", [])))

    def parse_gcov_file(self, file_path, directory=None):
        """
        Parse a single GCOV file and extract coverage data.
        """
        source_file = None
        with open(file_path, 'r') as file:
            for line in file:
                # Identify source file
                if line.startswith("        -:    0:Source:"):
                    source_file = line.split("Source:")[1].strip()
                    continue

                if source_file is None:
                    continue  # Skip until the source file is identified

                # Match GCOV execution counts: execution_count: line_number: line_content
                match = re.match(r'^\s*(\-|#####|\d+\*?|\d+):\s*(\d+):\s*(.*)', line)
                if match:
                    count, line_number, line_content = match.groups()
                    # get the line of code, preserving spaces
                    i_first_colon = line.find(':')
                    i_second_colon = line[i_first_colon+1:].find(':')
                    line_content = line[i_first_colon+i_second_colon+2:-1]

                    if (count == "-") or (count == "#####"):  # Line not executable or not executed
                        stripped_line = line_content.strip()
                        keywords = ("integer", "logical", "character", "real","complex", "type",
                                    "INTEGER", "LOGICAL", "CHARACTER", "REAL","COMPLEX", "TYPE",
                                    "module",  "private", "public", "contains", "interface",
                                    "MODULE",  "PRIVATE", "PUBLIC", "CONTAINS", "INTERFACE",
                                    "use", "implicit", "namelist",
                                    "USE", "IMPLICIT", "NAMELIST",
                                    "else", "end", "case", "continue",
                                    "ELSE", "END", "CASE", "CONTINUE",
                                    "!", "#", "&",
                                    "1","2","3","4","5","6","7","8","9") #format strings
                        if len(stripped_line) == 0 or stripped_line.startswith(keywords):
                            count = "-"  # Line is never executable
                        else:
                            count = 0    # Line is executable but not covered, possibly due to preprocessor directives
                    elif count.endswith("*"):  # Branch execution
                        count = int(count[:-1])
                    else:
                        count = int(count)

                    line_number = int(line_number)
                    # Aggregate counts and keep line content
                    current_count, current_line_content, directories = self.coverage_data[source_file][line_number]

                    if isinstance(count, int) and count > 0 and directory is not None:
                        directories.append(directory)

                    if isinstance(count, int):
                        if isinstance(current_count, int):
                           current_count += count
                        else:
                           current_count = count

                    if line_content != current_line_content and current_line_content != "":
                        print(f"Warning: Line content mismatch in {source_file} at line {line_number}")
                        print(f"  Previous line content: {current_line_content}")
                        print(f"  Current line content: {line_content}")
                        print(f"  Using previous line content and count for aggregation.")
                    else:
                        self.coverage_data[source_file][line_number] = (current_count, line_content, directories)

    def parse_directories(self, directories):
        """
        Parse all GCOV files from multiple directories.
        """
        for directory in directories:
            for file_path in glob(os.path.join(directory, "*.gcov")):
                self.parse_gcov_file(file_path, os.path.basename(directory))

    def save_aggregated_coverage(self, output_directory):
        """
        Save the aggregated coverage data for each source file.
        """
        full_code_tot = 0
        full_code_coverage = 0
        os.makedirs(output_directory, exist_ok=True)

        # sort files alphabetically
        sorted_files = sorted(list(self.coverage_data.keys()))

        for source_file in sorted_files:
            coverage = self.coverage_data[source_file]
            num_lines_tot = 0
            num_lines_exec = 0
            # Use the source file name to create an output file, keeping info on the source directory
            source_filename_parts = source_file.split('/')
            output_name = (source_filename_parts[-2]).upper() + '_' + source_filename_parts[-1]
            output_file = os.path.join(output_directory, f"{output_name}_aggregated.gcov")
            with open(output_file, 'w') as file:
                file.write(f"Source: {source_file}\n")
                for line_number, (count, line_content, directories) in sorted(coverage.items()):
                    # put back gcov synthax, for easier visual identification of unexecuted code
                    if count==0 or count=='#':
                        count="#####"
                    #file.write(f"{count:>6}: {line_number:>6}: {line_content:<120}: {', '.join(directories)}\n")
                    file.write(f"{count:>12}: {line_number:>6}: {line_content}\n")

                    # gather stats for file
                    if count!='-':
                        num_lines_tot = num_lines_tot+1
                        if isinstance(count, int) and count>0:
                            num_lines_exec = num_lines_exec+1

            # print stats on current file and add to total
            if num_lines_tot>0:
                print("{} {:6.2f}%   ({}/{})".format(source_file.ljust(50), 100*float(num_lines_exec)/num_lines_tot, num_lines_exec,num_lines_tot))
                full_code_tot = full_code_tot + num_lines_tot
                full_code_coverage = full_code_coverage + num_lines_exec

        print("Total code coverage {:.2f}% ({}/{})".format(100*float(full_code_coverage)/full_code_tot,full_code_coverage,full_code_tot))


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Aggregate GCOV files for a Fortran program with multiple source files.")
    parser.add_argument("gcov_dirs", nargs='+', help="Directories containing GCOV files (multiple directories allowed).")
    parser.add_argument("output_dir", help="Directory to save aggregated coverage data.")
    args = parser.parse_args()

    aggregator = GCovParser()
    aggregator.parse_directories(args.gcov_dirs)
    aggregator.save_aggregated_coverage(args.output_dir)
    print(f"Aggregated coverage data saved in directory: {args.output_dir}")
