# Script to merge coverage files generated by gcov
# Author: Noe Brucy, Tine Colman, Corentin Cadiou
# Known issues:
# - in rt_spectra, gcov identified some variable declarations as executed.
# - in turb_force_utils, stop is identified as a branch

import os
import re
import sys
from collections import defaultdict
from glob import glob

class GCovParser:
    def __init__(self):
        # Dictionary to store data as {source_file: {line_number: (execution_count, line_content, which_tests)}}
        self.coverage_data = defaultdict(lambda: defaultdict(lambda: ("-", "", [])))

    def parse_gcov_file(self, file_path, directory=None):
        """
        Parse a single GCOV file and extract coverage data.
        """
        source_file = None
        with open(file_path, 'r') as file:
            for line in file:
                # Identify source file, which is written at the top of the file
                if line.startswith("        -:    0:Source:"):
                    source_file = line.split("Source:")[1].strip()
                    continue

                # split the info in the line into counts, line number and line content
                i_first_colon = line.find(':')
                #skip if the line is weird
                if i_first_colon==-1 or i_first_colon>30:
                    continue
                i_second_colon = i_first_colon + 1 + line[i_first_colon+1:].find(':')
                count = line[:i_first_colon].strip()
                line_number = line[i_first_colon+1:i_second_colon].strip()
                line_content = line[i_second_colon+1:-1]

                if count in ("-", "#####"):  # Line not executable or not executed
                    stripped_line = line_content.strip()
                    keywords = ('integer', 'logical', 'character', 'real', 'complex',
                                'type', 'module', 'private', 'public', 'contains',
                                'interface', 'use ', 'implicit', 'namelist', 'else',
                                'end', 'case', 'continue', '!', '#', '&',
                                '1', '2', '3', '4', '5', '6', '7', '8', '9') # format strings
                    if len(stripped_line) == 0 or stripped_line.lower().startswith(keywords):
                        count = "-"  # Line is never executable
                    else:
                        count = 0    # Line is executable but not covered, possibly due to preprocessor directives
                elif count.endswith("*"):  # Branch execution
                    count = int(count[:-1])
                else:
                    count = int(count)

                line_number = int(line_number)
                # Aggregate counts and keep line content
                current_count, current_line_content, directories = self.coverage_data[source_file][line_number]

                if isinstance(count, int) and count > 0 and directory is not None:
                    directories.append(directory)

                if isinstance(count, int):
                    if isinstance(current_count, int):
                        current_count += count
                    else:
                        current_count = count

                if line_content != current_line_content and current_line_content != "":
                    print(f"Warning: Line content mismatch in {source_file} at line {line_number}",file=sys.stderr)
                    print(f"  Previous line content: {current_line_content}", file=sys.stderr)
                    print(f"  Current line content: {line_content}", file=sys.stderr)
                    print("  Using previous line content and count for aggregation.", file=sys.stderr)
                else:
                    self.coverage_data[source_file][line_number] = (current_count, line_content, directories)

    def parse_directories(self, directories):
        """
        Parse all GCOV files from multiple directories.
        """
        for directory in directories:
            for file_path in glob(os.path.join(directory, "*.gcov")):
                self.parse_gcov_file(file_path, os.path.basename(directory))

    def save_aggregated_coverage(self, output_directory):
        """
        Save the aggregated coverage data for each source file.
        """
        full_code_tot = 0
        full_code_coverage = 0
        os.makedirs(output_directory, exist_ok=True)

        # output file to store the results
        report_filename = 'coverage_report.txt'
        f = open(report_filename, 'w')

        # sort files alphabetically
        sorted_files = sorted(self.coverage_data.keys())

        for source_file in sorted_files:
            coverage = self.coverage_data[source_file]
            num_lines_tot = 0
            num_lines_exec = 0
            # Use the source file name to create an output file, keeping info on the source directory
            *_head, parent_folder, fname = source_file.split('/')
            output_name = f"{parent_folder.upper()}_{fname}"
            output_file = os.path.join(output_directory, f"{output_name}_aggregated.gcov")
            with open(output_file, 'w') as file:
                file.write(f"Source: {source_file}\n")
                for line_number, (count, line_content, directories) in sorted(coverage.items()):
                    # put back gcov synthax, for easier visual identification of unexecuted code
                    if count==0 or count=='#':
                        count="#####"
                    #file.write(f"{count:>6}: {line_number:>6}: {line_content:<120}: {', '.join(directories)}\n")
                    file.write(f"{count:>12}: {line_number:>6}: {line_content}\n")

                    # gather stats for file
                    if count!='-':
                        num_lines_tot = num_lines_tot+1
                        if isinstance(count, int) and count>0:
                            num_lines_exec = num_lines_exec+1

            # print stats on current file and add to total
            if num_lines_tot>0:
                coverage = 100 * num_lines_exec / num_lines_tot
                print(f"{source_file:50s} {coverage:6.2f}%   ({num_lines_exec}/{num_lines_tot})", file=f)
                full_code_tot = full_code_tot + num_lines_tot
                full_code_coverage = full_code_coverage + num_lines_exec

        coverage = 100*full_code_coverage/full_code_tot
        print(f"Total code coverage {coverage:.2f}% ({full_code_coverage}/{full_code_tot})", file=f)
        print(f"\033[92mTotal code coverage {coverage:.2f}% ({full_code_coverage}/{full_code_tot})\033[0m")
        print("Coverage statistics writen to file:",report_filename)
        f.close()

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Aggregate GCOV files for a Fortran program with multiple source files.")
    parser.add_argument("gcov_dirs", nargs='+', help="Directories containing GCOV files (multiple directories allowed).")
    parser.add_argument("output_dir", help="Directory to save aggregated coverage data.")
    args = parser.parse_args()

    aggregator = GCovParser()
    aggregator.parse_directories(args.gcov_dirs)
    aggregator.save_aggregated_coverage(args.output_dir)
    print(f"Aggregated coverage data saved in directory: {args.output_dir}")
