# Script to merge coverage files generated by gcov
# Author: Noe Brucy, Tine Colman, Corentin Cadiou
#
# Every line of the aggregated files is in one of four states:
#   <count>  executed that many times
#   #####    compiled, but never executed
#   -----    never compiled by any build; counted as uncovered
#   -        not executable (comment, declaration, continuation line, ...)
# Telling "-----" from "-" needs the -D flags of every build, which
# run_test_suite.sh records in build_records/ (passed with --build-records).
#
# Known issues:
# - in rt_spectra, gcov identified some variable declarations as executed.
# - in turb_force_utils, stop is identified as a branch

import json
import os
import re
import sys
from collections import defaultdict
from glob import glob

from gcov_preprocessor import parse_defines, unbuilt_lines, label_of


def split_or(expr):
    """Top-level || operands of a condition, [] if it is not a disjunction."""
    parts, depth, cur = [], 0, ""
    i = 0
    while i < len(expr):
        c = expr[i]
        if c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
        if depth == 0 and expr.startswith("||", i):
            parts.append(cur); cur = ""; i += 2; continue
        cur += c; i += 1
    parts.append(cur)
    return [p for p in parts if p] if len(parts) > 1 else []


def merge_gates(rows):
    """Fold equivalent conditions together and resolve disjunctions.

    `#if X` and `#elif X` gate the same code and are already one string by the
    time they get here. What is left is `#if A || B`: rather than inventing a
    category for every combination, charge it to whichever operand is the
    bigger cause in its own right.
    """
    solo = defaultdict(int)
    for n, _src, gate in rows:
        if not split_or(gate):
            solo[gate] += n

    def resolve(gate):
        atoms = split_or(gate)
        if not atoms:
            return gate
        best = max(atoms, key=lambda a: (solo.get(a, 0), -len(a)))
        return best if solo.get(best, 0) else gate

    merged = defaultdict(int)
    per_file = defaultdict(lambda: defaultdict(int))
    for n, src, gate in rows:
        g = resolve(gate)
        merged[g] += n
        per_file[src][g] += n
    return merged, per_file


# A line inside a never-compiled block carries no gcov verdict, so whether it
# would have been executable has to be read off the source. gcov decides this
# for every line it did compile; these patterns only ever apply to the lines it
# did not. Checked against gcov's own verdict on the compiled lines of a full
# run, they agree on 96.8% of them, the rest being multi-line statements whose
# count gcov attributes to one arbitrary line of the statement.
DECLARATION = re.compile(r"""^(integer|real|double\s*precision|complex|logical|
    character|type|class|procedure|dimension|allocatable|pointer|target|save|
    parameter|common|equivalence|data|external|intrinsic|optional|intent|public|
    private|protected|sequence|generic|final|import|abstract|enum|enumerator|
    volatile|asynchronous|bind|value|namelist|implicit|use|module|
    contains|interface|include|format)\b""", re.I | re.X)
END_OF_BLOCK = re.compile(r"^end\s*(if|do|select|where|forall|associate|block|"
                          r"type|interface|module|program|subroutine|function|"
                          r"critical|enum)?\s*\w*\s*$", re.I)
ELSE_IF = re.compile(r"^else\s*if\b", re.I)   # the condition is evaluated
NO_CODE = re.compile(r"^else\b|^case\b|^continue\b|^\d+\s*(continue|format)\b", re.I)
FUNCTION = re.compile(r"\bfunction\b", re.I)
# Lines gcov sometimes attributes code to, but that cannot meaningfully be
# covered, so they are treated as not executable whatever gcov says:
#   end module      an artefact. amr_commons, used by nearly every routine,
#                   reports "#####" while pm_commons reports "-"; none of the
#                   modules in a full run is ever covered.
#   end subroutine  a routine has one exit block, and gcov attaches it to the
#   end function    closing line only when the routine happens not to end with
#                   an explicit `return` or a `format` statement. The marker
#                   therefore tracks source layout, not coverage: of 642
#                   `end subroutine` in a full run, 368 were counted and 157
#                   were not, split by exactly that.
#   NNN format      a format statement never executes.
#   declarations    gfortran emits code at routine entry for allocatable
#                   locals (marked unallocated, freed again on exit) and for
#                   arrays sized at run time, e.g. dimension(1:ncpu), and gcov
#                   attributes that code to the declaration. The count is
#                   just a multiple of the number of calls, and whether it
#                   appears depends on which kind of locals a routine has.
NOT_COVERABLE = re.compile(r"^end\s*(module|subroutine|function)\b"
                           r"|^\d+\s+format\b", re.I)

# The directories bin/Makefile takes sources from (its VPATH, for every
# SOLVER), searched for files that end up without any coverage data.
SOURCE_DIRS = ("amr", "aton", "hydro", "io", "mhd", "pm", "poisson", "rhd",
               "rt", "turb")


def strip_comment(line):
    """Drop a trailing ! comment, ignoring ! inside a string."""
    out, quote = [], None
    for c in line:
        if quote:
            out.append(c)
            if c == quote:
                quote = None
        elif c in "\'\"":
            quote = c
            out.append(c)
        elif c == '!':
            break
        else:
            out.append(c)
    return ''.join(out)


def is_declaration(line):
    """A specification statement. `real function f(x)` is a routine header."""
    return bool(DECLARATION.match(line)) and not FUNCTION.search(line.split('::')[0])


def executable_lines(lines):
    """
    Line numbers of the lines that would carry code if they were compiled.
    Comments, blanks, declarations, `end`/`else`/`case` and the continuation
    lines of a statement do not: the statement is counted once, on its head.
    """
    code, continued = set(), False
    for number, raw in enumerate(lines, 1):
        line = raw.strip()
        was_continued = continued
        if line and line[0] not in '!#':
            continued = strip_comment(line).rstrip().endswith('&')
        if not line or line[0] in '!#' or was_continued:
            continue
        line = strip_comment(line).strip()   # `endif ! why` is still an endif
        if not line:
            continue
        if ELSE_IF.match(line):
            code.add(number)
        elif NO_CODE.match(line) or END_OF_BLOCK.match(line):
            continue
        elif is_declaration(line):
            continue
        else:
            code.add(number)
    return code



def continuation_heads(lines):
    """
    Map the line number of every continuation line to the line that starts
    its statement. Free-form Fortran continues a statement when the line ends
    with "&" outside a comment; a comment or preprocessor line in between does
    not break the continuation.
    """
    heads, current, continued = {}, None, False
    for number, raw in enumerate(lines, 1):
        line = raw.strip()
        if not line or line[0] in '!#':
            continue
        if continued and current is not None:
            heads[number] = current
        else:
            current = number
        continued = strip_comment(line).rstrip().endswith('&')
    return heads


def merge_multiline(coverage):
    """
    Give a statement that spans several lines a single count, on its first
    line. gcov picks one line of the statement to carry the count, and which
    one is not predictable: a continuation can hold the count while the line
    that starts the statement reads "-". Both spellings describe one statement
    executing once, so the count is moved to the head and the continuation
    lines become not executable. Returns how many counts had to be moved.
    """
    if not coverage:
        return 0
    last = max(coverage)
    lines = [""] * last
    for number, (_count, content, _dirs) in coverage.items():
        if 1 <= number <= last:
            lines[number-1] = content
    moved = 0
    for number, head in sorted(continuation_heads(lines).items()):
        if number not in coverage or head not in coverage:
            continue
        count, content, dirs = coverage[number]
        head_count, head_content, head_dirs = coverage[head]
        if isinstance(count, int):
            if not isinstance(head_count, int) or count > head_count:
                head_count = count
                moved += 1
            for d in dirs:
                if d not in head_dirs:
                    head_dirs.append(d)
            coverage[head] = (head_count, head_content, head_dirs)
        coverage[number] = ("-", content, [])
    return moved


class GCovParser:
    def __init__(self, source_root=".."):
        # Dictionary to store data as {source_file: {line_number: (execution_count, line_content, which_tests)}}
        self.coverage_data = defaultdict(lambda: defaultdict(lambda: ("-", "", [])))
        self.source_root = source_root
        self.notbuilt = {}  # {source_file: {line_number: gating directive}}
        # {source_file: {(test label, run)}}: the builds that compiled it
        self.built_by = defaultdict(set)

    def parse_gcov_file(self, file_path, directory=None):
        """
        Parse a single GCOV file and extract coverage data. Returns the
        source file it describes.
        """
        source_file = None
        with open(file_path, 'r') as file:
            for line in file:
                # Identify source file, which is written at the top of the file
                if line.startswith("        -:    0:Source:"):
                    source_file = line.split("Source:")[1].strip()
                    continue

                # split the info in the line into counts, line number and line content
                i_first_colon = line.find(':')
                #skip if the line is weird
                if i_first_colon==-1 or i_first_colon>30:
                    continue
                i_second_colon = i_first_colon + 1 + line[i_first_colon+1:].find(':')
                count = line[:i_first_colon].strip()
                line_number = line[i_first_colon+1:i_second_colon].strip()
                line_content = line[i_second_colon+1:-1]

                # "-" is left as it is. Whether such a line is genuinely not
                # executable or was simply never compiled is decided by
                # mark_unbuilt(), from the preprocessor structure of the
                # source, rather than guessed at from the text of the line.
                if count == "#####":  # Line not executed
                    count = 0
                elif count.endswith("*"):
                    # The line ran, but one of its blocks did not. That block
                    # is often compiler-generated (a failed allocation, the
                    # inside of an intrinsic), so the line counts as executed.
                    count = int(count[:-1])
                elif count != "-":
                    count = int(count)

                line_number = int(line_number)
                # line 0 holds gcov's header records, not source lines
                if line_number == 0:
                    continue
                # Aggregate counts and keep line content
                lines = self.coverage_data[source_file]
                # Counts can only be added up if every .gcov file was made
                # from the same version of the source.
                if line_number in lines and lines[line_number][1] != line_content:
                    sys.exit(f"Error: line {line_number} of {source_file} differs between .gcov files\n"
                             f"  earlier files: {lines[line_number][1]}\n"
                             f"  {file_path}: {line_content}\n"
                             "The .gcov files were made from different versions of the source.")
                current_count, _, directories = lines[line_number]

                if isinstance(count, int) and count > 0 and directory is not None:
                    directories.append(directory)

                if isinstance(count, int):
                    if isinstance(current_count, int):
                        current_count += count
                    else:
                        current_count = count

                self.coverage_data[source_file][line_number] = (current_count, line_content, directories)
        return source_file

    def parse_directories(self, directories):
        """
        Parse all GCOV files from multiple directories, one per test. The
        files of a test may sit in subdirectories, one per run of the test
        (e.g. with different builds); their counts are summed.
        """
        for directory in directories:
            # normpath first: a trailing slash would make basename empty
            label = os.path.basename(os.path.normpath(directory))
            for file_path in glob(os.path.join(directory, "**", "*.gcov"), recursive=True):
                source_file = self.parse_gcov_file(file_path, label)
                # gcov writes a .gcov file for every source file a build
                # compiled, whether it ran or not: this is how we know which
                # builds compiled which file
                run = os.path.relpath(os.path.dirname(file_path), directory)
                self.built_by[source_file].add((label, "" if run == "." else run))

    def macro_sets_of(self, source_file, records, every_build, unmatched):
        """
        The -D flags of the builds that compiled source_file. When one of
        them has no build record, the flags of every build: that can only
        overlook never-compiled lines, not invent them.
        """
        sets = []
        for label, run in sorted(self.built_by[source_file]):
            matched = [r["macros"] for r in records if describes(r, label, run)]
            if not matched:
                unmatched.add((label, run))
                return every_build
            sets += matched
        return distinct(sets)

    def mark_unbuilt(self, records):
        """
        Find the lines that no build ever compiled, by replaying the
        preprocessor directives of each source file against the -D flags of
        the builds that compiled it. Checking a file against every build
        instead would take, e.g., the NENER>0 of hydro builds as proof that
        a block of mhd/umuscl.f90 was compiled.
        """
        every_build = distinct(r["macros"] for r in records)
        unmatched = set()
        for source_file, coverage in self.coverage_data.items():
            path = os.path.normpath(os.path.join(self.source_root, source_file))
            if not os.path.exists(path):
                continue
            with open(path, errors="replace") as file:
                lines = file.read().split("\n")
            macro_sets = self.macro_sets_of(source_file, records, every_build, unmatched)
            dead, undecided = unbuilt_lines(lines, macro_sets)
            for number, directive in undecided:
                print(f"Warning: cannot evaluate `{directive}` at {source_file}:{number} "
                      f"for every build; the code it gates is taken as compiled",
                      file=sys.stderr)
            # A count means gcov saw the line compiled, whatever the
            # directives say: the replay of the preprocessor is wrong there.
            # The count wins, so the line is still reported correctly.
            wrong = sorted(n for n in dead if n in coverage and isinstance(coverage[n][0], int))
            if wrong:
                print(f"Warning: {len(wrong)} lines of {source_file} have gcov counts but were "
                      f"judged never compiled (first: line {wrong[0]}, `{label_of(dead[wrong[0]])}`)",
                      file=sys.stderr)
            if dead:
                # A declaration or a comment in a dead block is still not a
                # line that could have run, so it stays "-" rather than
                # becoming an uncovered "-----".
                code = executable_lines(lines)
                dead = {n: gate for n, gate in dead.items() if n in code}
            if dead:
                self.notbuilt[source_file] = dead
        for label, run in sorted(unmatched):
            print(f"Warning: no build record for {label}{f' (run {run})' if run else ''}; "
                  "the files it compiled are checked against every build", file=sys.stderr)

    def files_without_data(self):
        """
        Source files no .gcov file mentions, as paths relative to source_root
        like the Source: paths. A directory where that holds for every file
        is given as a single entry.
        """
        seen = {os.path.normpath(s) for s in self.coverage_data}
        entries = []
        for d in SOURCE_DIRS:
            files = sorted(glob(os.path.join(self.source_root, "..", d, "*.f90")) +
                           glob(os.path.join(self.source_root, "..", d, "*.F")))
            files = [os.path.relpath(p, self.source_root) for p in files]
            missing = [p for p in files if p not in seen]
            if missing and len(missing) == len(files):
                entries.append(f"{os.path.dirname(files[0])}/  (all {len(files)} files)")
            else:
                entries += missing
        return entries

    def save_aggregated_coverage(self, output_directory):
        """
        Save the aggregated coverage data for each source file.
        """
        full_code_tot = 0
        full_code_coverage = 0
        full_code_notbuilt = 0
        gcov_directory = os.path.join(output_directory, "gcov_files")
        os.makedirs(gcov_directory, exist_ok=True)

        # output file to store the results, alongside the aggregated gcov files
        report_filename = os.path.join(output_directory, 'coverage_report.txt')
        f = open(report_filename, 'w')
        print("Coverage per source file.\n\n"
              "  covered    percentage of the executable lines that ran\n"
              "  ran/total  lines that ran / lines that could run in some build\n"
              "  not built  of those, the lines no build of this run compiled at all,\n"
              "             because they sit behind a preprocessor directive none of the\n"
              "             builds enabled. They count as uncovered: RAMSES is recompiled\n"
              "             when a physics module is switched on, so reaching them needs\n"
              "             another build variant rather than another namelist.\n"
              "             Broken out in coverage_notbuilt.txt.\n",
              file=f)
        print(f"{'file':50s} {'covered':>8}  {'ran/total':>16}  {'not built':>9}", file=f)
        print("-" * 90, file=f)

        # which tests reached which line, kept apart so the .gcov files stay readable
        which_tests = {}
        # (count, source_file, directive) for every never-compiled block
        notbuilt_rows = []

        # sort files alphabetically
        sorted_files = sorted(self.coverage_data.keys())

        moved_total = 0
        for source_file in sorted_files:
            coverage = self.coverage_data[source_file]
            # one statement, one counted line: see merge_multiline()
            moved_total += merge_multiline(coverage)
            dead = self.notbuilt.get(source_file, {})
            num_lines_tot = 0
            num_lines_exec = 0
            num_lines_notbuilt = 0
            notbuilt_here = defaultdict(int)
            hits = {}
            # Use the source file name to create an output file, keeping info on the source directory
            *_head, parent_folder, fname = source_file.split('/')
            output_name = f"{parent_folder.upper()}_{fname}"
            output_file = os.path.join(gcov_directory, f"{output_name}_aggregated.gcov")
            with open(output_file, 'w') as file:
                file.write(f"Source: {source_file}\n")
                for line_number, (count, line_content, directories) in sorted(coverage.items()):
                    # put back gcov synthax, for easier visual identification of unexecuted code
                    gate = dead.get(line_number)
                    stripped = line_content.strip()
                    if NOT_COVERABLE.match(stripped) or is_declaration(stripped):
                        count = "-"
                    elif gate is not None and not isinstance(count, int):
                        count = "-----"  # never compiled, not a gap a namelist can close
                        num_lines_notbuilt = num_lines_notbuilt+1
                        notbuilt_here[re.sub(r'\s+', ' ', gate).strip()] += 1
                    elif count==0:
                        count = "#####"
                    file.write(f"{count:>12}: {line_number:>6}: {line_content}\n")

                    # gather stats for file
                    # "-----" is uncovered, not outside the measurement
                    if count!='-':
                        num_lines_tot = num_lines_tot+1
                        if isinstance(count, int) and count>0:
                            num_lines_exec = num_lines_exec+1
                    # only lines that still count: a line we have just ruled
                    # not executable must not appear in coverage_tests.json
                    # either, or a test could "cover" more lines than exist
                    if directories and count not in ('-', '-----', '#####'):
                        hits[line_number] = sorted(set(directories))

            if hits:
                which_tests[source_file] = hits
            for gate, n in notbuilt_here.items():
                notbuilt_rows.append((n, source_file, gate))

            # print stats on current file and add to total
            if num_lines_tot>0:
                percent = 100 * num_lines_exec / num_lines_tot
                print(f"{source_file:50s} {percent:7.2f}%  {f'{num_lines_exec}/{num_lines_tot}':>16}"
                      f"  {num_lines_notbuilt if num_lines_notbuilt else '':>9}", file=f)
                full_code_tot = full_code_tot + num_lines_tot
                full_code_coverage = full_code_coverage + num_lines_exec
                full_code_notbuilt = full_code_notbuilt + num_lines_notbuilt

        total_percent = 100*full_code_coverage/full_code_tot if full_code_tot else 0.0
        print("-" * 90, file=f)
        print(f"{'TOTAL':50s} {total_percent:7.2f}%  {f'{full_code_coverage}/{full_code_tot}':>16}"
              f"  {full_code_notbuilt:>9}", file=f)

        missing = self.files_without_data()
        if missing:
            print("\n\nSource files without any coverage data, left out of the totals above:\n"
                  "no build of this run compiled them, or they hold no executable code\n"
                  "(modules of variables and parameters). Expected here are rhd/ and aton/,\n"
                  "which are not actively supported, and the obsolete\n"
                  "poisson/multigrid_topdown.f90.\n", file=f)
            for entry in missing:
                print(f"  {entry}", file=f)
        f.close()

        # which tests reached which line: a sidecar, because listing them in the
        # .gcov files makes the widely-covered lines unreadably long
        with open(os.path.join(output_directory, "coverage_tests.json"), 'w') as file:
            json.dump(which_tests, file, separators=(",", ":"), sort_keys=True)

        # what the preprocessor kept out of every build
        self.save_notbuilt_report(output_directory, notbuilt_rows, full_code_notbuilt)

        print(f"\033[92mTotal code coverage {total_percent:.2f}% ({full_code_coverage}/{full_code_tot})\033[0m")
        if full_code_notbuilt:
            print(f"{full_code_notbuilt} lines were never compiled by any build (see coverage_notbuilt.txt)")
        if moved_total:
            print(f"{moved_total} counts moved to the first line of their statement")
        print("Coverage statistics writen to file:",report_filename)

    def save_notbuilt_report(self, output_directory, notbuilt_rows, total):
        """
        Count the never-compiled lines, by preprocessor directive and by file.
        """
        by_gate, per_file = merge_gates(notbuilt_rows)
        with open(os.path.join(output_directory, "coverage_notbuilt.txt"), 'w') as f:
            print("Lines no build of this run compiled, because they sit behind a\n"
                  "preprocessor directive none of the builds enabled. No namelist can\n"
                  "reach them: closing these means adding a build variant, or deciding\n"
                  "they are permanently out of scope. They count as uncovered in\n"
                  "coverage_report.txt.\n\n"
                  "`#if X` and `#elif X` are counted together, and a condition of the\n"
                  "form `A || B` is charged to whichever operand is the larger cause on\n"
                  "its own.\n", file=f)
            print("=== by directive ===\n", file=f)
            for gate, n in sorted(by_gate.items(), key=lambda x: (-x[1], x[0])):
                print(f"{n:6d}  {label_of(gate)}", file=f)
            print(f"\n{total:6d}  TOTAL", file=f)

            print("\n\n=== by file ===\n", file=f)
            totals = {s: sum(g.values()) for s, g in per_file.items()}
            for source_file in sorted(totals, key=lambda s: -totals[s]):
                print(f"{totals[source_file]:6d}  {source_file}", file=f)
                for gate, n in sorted(per_file[source_file].items(), key=lambda x: (-x[1], x[0])):
                    print(f"        {n:6d}  {label_of(gate)}", file=f)
                print("", file=f)


def build_records(path):
    """
    Read the build records run_test_suite.sh writes, as
    {"test": "hydro/advect1d", "run": <timestamp, "" if not recorded>,
    "macros": <the -D flags of the build>}. `path` is the build_records/
    directory, or a single file holding records, such as the
    coverage_metadata.txt of coverage directories made before build_records/.
    """
    records = []
    if not path or not os.path.exists(path):
        return records
    files = sorted(glob(os.path.join(path, "*.txt"))) if os.path.isdir(path) else [path]
    lines = [line for f in files for line in open(f, errors="replace")]
    for line in lines:
        m = re.match(r'^test\s*:\s*(\S+)', line)
        if m:
            records.append({"test": m.group(1), "run": "", "defines": ""})
            continue
        m = re.match(r'^\s+(run|defines)\s*:\s*(.*)$', line)
        if m and records:
            records[-1][m.group(1)] = m.group(2).strip()
    return [{"test": r["test"], "run": r["run"], "macros": parse_defines(r["defines"])}
            for r in records if r["defines"]]


def describes(record, label, run):
    """
    Whether a build record is that of `run` of the test labelled `label`.
    Labels are <category>_<test>, or just <test> in coverage directories made
    before that. `run` is the subdirectory holding the run's .gcov files, ""
    when a test's files are not split by run.
    """
    names = (record["test"].replace("/", "_"), os.path.basename(record["test"]))
    return label in names and (not run or record["run"] == run)


def distinct(macro_sets):
    """The different builds among macro_sets, in order."""
    out = []
    for ms in macro_sets:
        if ms not in out:
            out.append(ms)
    return out


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Aggregate GCOV files for a Fortran program with multiple source files.")
    parser.add_argument("gcov_dirs", nargs='+', help="Directories containing GCOV files, one per test "
                             "(searched recursively, so each may hold one subdirectory per run).")
    parser.add_argument("output_dir", help="Directory to save aggregated coverage data.")
    parser.add_argument("--build-records", default=None,
                        help="The build_records/ directory, for the -D flags of each build "
                             "(or the coverage_metadata.txt of older coverage directories).")
    parser.add_argument("--source-root",
                        default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "bin"),
                        help="Directory the Source: paths in the .gcov files are relative "
                             "to (default: the bin directory, where gcov runs).")
    args = parser.parse_args()

    aggregator = GCovParser(source_root=args.source_root)
    aggregator.parse_directories(args.gcov_dirs)
    records = build_records(args.build_records)
    if records:
        print(f"Read {len(records)} build records ({len(distinct(r['macros'] for r in records))} "
              f"distinct build configurations) from {args.build_records}")
        aggregator.mark_unbuilt(records)
    else:
        print("No build records given: never-compiled lines will be reported as not executable.",
              file=sys.stderr)
    aggregator.save_aggregated_coverage(args.output_dir)
    print(f"Aggregated coverage data saved in directory: {args.output_dir}")
