# This file was initially copied from https://github.com/Shamrock-code/Shamrock/blob/main/.github/workflows/on_completed_pr_workflow.yml


name: on PR (completed)

# This workflow is triggered by the completion of the "on PR" workflow
# which can be use to perform reporting while allowing the use of the pull_request
# event to trigger the pr workflow.


on:
  workflow_run:
    workflows: ['on PR']
    types:
    - completed



jobs:
  comment_with_results:
    runs-on: ubuntu-latest

    steps:

     - name: 'Merge all files into a single file'
       shell: bash
       run: |
          # Create a merged file
          merged_file="test_suite.log"

          echo " -- sort filelist"
          # add local set otherwise sort is weird
          LC_ALL=C filelist=$(echo *.txt | tr ' ' '\n' | sort)
          echo "$filelist"

          # Append each .txt file into the merged file in sorted order
          for txt_file in $filelist; do
            echo "Appending: $txt_file"
            cat "$txt_file" >> "$merged_file"
          done

          # Create a unique pdf
          pdfunite *.pdf test_results.pdf


     - name: Upload the resulting pdf
       uses: actions/upload-artifact@v4
       id: artifact-upload-step-pdf
       with:
          name: test_results.pdf
          path: test_results.pdf

     - name: Upload the resulting log
       uses: actions/upload-artifact@v4
       id: artifact-upload-step-log
       with:
          name: test_suite.log
          path: test_suite.log

     # See https://github.com/actions/upload-artifact/issues/50#issuecomment-1856471599
     - name: Report artifacts url
       run: echo "Test suite results:[PDF link](${{ steps.artifact-upload-step-pdf.outputs.artifact-url }}) (can expire)" > comment.md

     - name: 'Comment merged report on the PR'
       uses: thollander/actions-comment-pull-request@v3
       with:
          file-path: comment.md
          comment-tag: workflow_report
          mode: recreate
          create-if-not-exists: true
          pr-number: ${{ steps.read_pr.outputs.pr_number }}
