name: on PR

# Controls when the workflow will run
on: [pull_request]

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:


  upload_pr_detail:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr_number.txt

      - uses: actions/upload-artifact@v4
        with:
          name: test_pr_number
          path: ./pr_number.txt


  tests:
    name: Test Ramses
    uses: ./.github/workflows/tests.yaml
